apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: boilerplate-master-pr-check-pipelinerun-
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/openshift/boilerplate
      - name: revision
        value: master
      - name: pathInRepo
        value: .tekton/boilerplate-master-pr-check.yaml
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
